import path from 'node:path';
import chokidar from 'chokidar';
import { VIDEOS_DIR } from './paths.js';
import { broadcastReload } from './ws.js';
import { qaAutoRunner } from './qa/auto.js';

/**
 * Watch each `videos/<slug>/{manifest.json, narration/*, manim/*, qa-report.json}`
 * for changes and emit a debounced `preview:reload` over WS so any open editor
 * view re-fetches data + remounts the player.
 *
 * Chokidar 4.x removed native glob support, so we watch `VIDEOS_DIR` recursively
 * and filter event paths manually. `awaitWriteFinish` prevents partial mp4
 * writes during a render from triggering a flood of reloads.
 *
 * macOS kqueue-FD doctrine: watching a deep tree with many sibling subdirs
 * opens 2000+ kqueue FDs, which exhausts the per-process FD pool and makes
 * `posix_spawn` fail with
 * `EBADF` when the editor server later tries to spawn `claude` for a chat
 * turn. The symptom is "chat turn failed: spawn EBADF" + a dead server.
 * Defences below:
 *   1. `depth: 3` — limit recursion so we don't descend into asset folders'
 *      sub-trees we don't care about.
 *   2. `ignored` list expanded to skip the high-fanout dirs that don't
 *      drive any preview-reload signal: `paper-md-assets/`,
 *      `manim-last-frames/`, `media/` (Manim's per-scene intermediate cache
 *      — Tex/, images/, videos/ subdirs that grow to thousands of files per
 *      slug), `public/`, dotfiles. (We DO watch `images/`, `diagrams/`,
 *      `pages/` — those carry reload-worthy regenerations.)
 *   3. `awaitWriteFinish` kept (it polls but only on actively-changing
 *      files, so FD overhead is bounded by what's being written, not by
 *      the tree size).
 */
export function startWatcher(): void {
  const watcher = chokidar.watch(VIDEOS_DIR, {
    ignoreInitial: true,
    depth: 3,
    awaitWriteFinish: { stabilityThreshold: 400, pollInterval: 100 },
    ignored: (p: string) => {
      // Dotfiles (.cache/, .DS_Store, …) — never useful + .cache is high-fanout.
      if (/[/\\]\.[^/\\]/.test(p)) return true;
      // Renderer's mirror directory (we already track its sources).
      if (/[/\\]public[/\\]/.test(p)) return true;
      // Marker's image dump — hundreds of jpegs per paper, never reload-relevant.
      if (/[/\\]paper-md-assets[/\\]/.test(p)) return true;
      // Per-mp4 last-frame PNGs — regenerated by render-remotion as a side
      // effect; the manim/*.mp4 watch already drives any needed reload.
      if (/[/\\]manim-last-frames[/\\]/.test(p)) return true;
      // Manim's per-scene intermediate cache — Tex/, images/, videos/ partial
      // outputs that grow to thousands of files per slug and would otherwise
      // eat one kqueue FD each, exhausting the pool and breaking spawn().
      if (/[/\\]media[/\\]/.test(p)) return true;
      return false;
    },
  });

  const pending = new Map<string, NodeJS.Timeout>();

  const trigger = (filepath: string) => {
    const slug = slugFromPath(filepath);
    if (!slug) return;
    if (!isInteresting(filepath)) return;
    // Auto-run QA for any interesting change OTHER than qa-report.json
    // itself (avoids the runner re-triggering its own write).
    if (!filepath.endsWith('qa-report.json')) {
      qaAutoRunner.schedule(slug);
    }
    const existing = pending.get(slug);
    if (existing) clearTimeout(existing);
    pending.set(
      slug,
      setTimeout(() => {
        pending.delete(slug);
        broadcastReload(slug);
      }, 600),
    );
  };

  for (const evt of ['add', 'change', 'unlink'] as const) {
    watcher.on(evt, trigger);
  }
  watcher.on('error', (err) => {
    // eslint-disable-next-line no-console
    console.error('[watcher] error', err);
  });
}

function slugFromPath(filepath: string): string | null {
  const rel = path.relative(VIDEOS_DIR, filepath);
  if (rel.startsWith('..')) return null;
  const first = rel.split(path.sep)[0];
  return first ?? null;
}

function isInteresting(filepath: string): boolean {
  const rel = path.relative(VIDEOS_DIR, filepath);
  // rel is like "<slug>/manifest.json" or "<slug>/narration/beat-005.mp3".
  const parts = rel.split(path.sep);
  if (parts.length < 2) return false;
  const tail = parts.slice(1).join('/');
  if (tail === 'manifest.json') return true;
  if (tail === 'qa-report.json') return true;
  if (parts[1] === 'narration') return true;
  if (parts[1] === 'manim' && tail.endsWith('.mp4')) return true;
  // Cover image / diagram regenerations too — without these the watcher
  // would only fire for the manifest write, but if an asset got rewritten
  // in place under the same filename the manifest URL stays identical and
  // the player serves the stale cached bytes. The cache-bust query param
  // attached by PaperExplainerCore is what actually defeats the cache;
  // this just makes sure the reload event fires when the file changes.
  if (parts[1] === 'images') return true;
  if (parts[1] === 'diagrams') return true;
  if (parts[1] === 'pages') return true;
  // `paper-md-assets` intentionally excluded — already ignored at the
  // chokidar level (see startWatcher) because it's a hundreds-of-jpegs
  // dump from Marker that doesn't drive any reload signal but eats FDs.
  return false;
}
